[app_servers]
13.61.141.38 ansible_user=ubuntu ansible_ssh_private_key_file=/var/jenkins_home/.ssh/terraform.pem

[monitoring_servers]
51.20.77.124 ansible_user=ubuntu ansible_ssh_private_key_file=/var/jenkins_home/.ssh/terraform.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3
